#goal definition
string object_name
---
#result definition
grasp_set_skill_msgs/GraspCandidateArr grasp_candidates
int32 percentage
string skillStatus
---
#feedback
int32 percentage
string skillStatus
